/**
 * RootLayout Component
 * 
 * This component serves as the root layout for the Next.js application.
 * It wraps all pages and provides a consistent HTML structure, including
 * metadata (title and description) and a common language attribute.
 * 
 * Props:
 * - children (ReactNode): The content of the current page to be rendered.
 * 
 * Metadata:
 * - title (string): The title of the application, displayed in the browser tab.
 * - description (string): A brief description of the application, used for SEO.
 */
export const metadata = {
  title: 'Next.js', // Title of the application
  description: 'Generated by Next.js', // Description of the application
};

/**
 * RootLayout Function
 * 
 * This function defines the root layout structure for the application.
 * It includes the HTML and body tags, and renders the children (page content)
 * within the body.
 * 
 * @param {Object} props - The props passed to the component.
 * @param {ReactNode} props.children - The content of the current page.
 * @returns {JSX.Element} - The root layout structure.
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en"> {/* Set the language of the page to English */}
      <body>
        {children} {/* Render the content of the current page */}
      </body>
    </html>
  );
}